In [307]:
import numpy as np
import pandas as pd

In [308]:
df = pd.read_csv(r'retail_sales_dataset.csv')
product = pd.read_csv(r'product_catalog.csv')

Data exploration aur inspection

Dataset ko load karke in sawalon ke jawab dein:
- Total rows aur columns kitne hain?
- Har column ka data type kya hai?
- head(), tail(), info() aur describe() kya information dete hain?
- Har column mein missing values kitni hain?

In [309]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 654 entries, 0 to 653
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        654 non-null    str
 1   Order_Date      654 non-null    str
 2   Customer_ID     647 non-null    str
 3   City            648 non-null    str
 4   Product_ID      654 non-null    str
 5   Product_Name    654 non-null    str
 6   Category        654 non-null    str
 7   Quantity        649 non-null    float64
 8   Unit_Price_PKR  648 non-null    float64
 9   Discount_Rate   649 non-null    float64
 10  Payment_Method  647 non-null    str
 11  Order_Status    654 non-null    str
dtypes: float64(3), str(9)
memory usage: 61.4 KB

In [310]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product_ID      15 non-null     str
 1   Product_Name    15 non-null     str
 2   Category        15 non-null     str
 3   List_Price_PKR  15 non-null     int64
 4   Supplier        15 non-null     str
dtypes: int64(1), str(4)
memory usage: 732.0 bytes

In [311]:
df.dtypes

Order_ID              str
Order_Date            str
Customer_ID           str
City                  str
Product_ID            str
Product_Name          str
Category              str
Quantity          float64
Unit_Price_PKR    float64
Discount_Rate     float64
Payment_Method        str
Order_Status          str
dtype: object

In [312]:
product.dtypes

Product_ID          str
Product_Name        str
Category            str
List_Price_PKR    int64
Supplier            str
dtype: object

In [313]:
df.head()

,Order_ID,Order_Date,Customer_ID,City,Product_ID,Product_Name,Category,Quantity,Unit_Price_PKR,Discount_Rate,Payment_Method,Order_Status
0,ORD-10001,2025-11-10,CUST-008,Multan,P002,Keyboard,Electronics,4.0,3200.0,0.10,Card,Completed
1,ORD-10002,2025-09-19,CUST-071,Faisalabad,P002,Keyboard,Electronics,3.0,3200.0,0.20,Cash,Returned
2,ORD-10003,2025-12-05,CUST-071,Multan,P013,Face Wash,Beauty,3.0,780.0,0.10,Bank Transfer,Completed
3,ORD-10004,2025-02-03,CUST-050,Gujranwala,P013,Face Wash,Beauty,3.0,780.0,0.05,Cash,Completed
4,ORD-10005,2025-10-04,CUST-064,Islamabad,P013,Face Wash,Beauty,5.0,780.0,0.00,Cash,Completed

In [314]:
product.head()

  Product_ID    Product_Name     Category  List_Price_PKR          Supplier
0       P001  Wireless Mouse  Electronics            1800  PakTech Supplies
1       P002        Keyboard  Electronics            3200   Metro Wholesale
2       P003       USB-C Hub  Electronics            5400   Metro Wholesale
3       P004    Notebook Set   Stationery             650  PakTech Supplies
4       P005  Ballpoint Pens   Stationery             250     Prime Traders

In [315]:
df.tail()

,Order_ID,Order_Date,Customer_ID,City,Product_ID,Product_Name,Category,Quantity,Unit_Price_PKR,Discount_Rate,Payment_Method,Order_Status
649,ORD-10650,2025-02-14,CUST-061,Faisalabad,P015,Sunscreen,Beauty,3.0,1417.5,0.00,Cash,Completed
650,ORD-10013,2025-06-17,CUST-046,Faisalabad,P008,Storage Box,Home & Kitchen,4.0,1522.5,0.00,Cash,Completed
651,ORD-10050,2025-04-25,CUST-087,Faisalabad,P005,Ballpoint Pens,Stationery,1.0,250.0,0.05,Card,Completed
652,ORD-10104,2025-04-04,CUST-059,Rawalpindi,P005,Ballpoint Pens,Stationery,3.0,250.0,0.10,EasyPaisa,Returned
653,ORD-10251,2025-09-08,CUST-072,Multan,P008,Storage Box,Home & Kitchen,3.0,1450.0,0.00,Cash,Completed

In [316]:
product.tail()

   Product_ID      Product_Name Category  List_Price_PKR          Supplier
10       P011          Yoga Mat   Sports            2800     Prime Traders
11       P012  Resistance Bands   Sports            1600   Metro Wholesale
12       P013         Face Wash   Beauty             780       Urban Goods
13       P014       Moisturizer   Beauty            1650  PakTech Supplies
14       P015         Sunscreen   Beauty            1350     Prime Traders

In [317]:
df.describe()

         Quantity  Unit_Price_PKR  Discount_Rate
count  649.000000      648.000000     649.000000
mean     2.946071     2096.168210       0.081664
std      1.440761     1872.011902       0.073144
min      1.000000      225.000000       0.000000
25%      2.000000      819.000000       0.000000
50%      3.000000     1450.000000       0.050000
75%      4.000000     2800.000000       0.150000
max      5.000000     7560.000000       0.200000

In [318]:
product.describe()

       List_Price_PKR
count       15.000000
mean      2058.666667
std       1923.849811
min        250.000000
25%        865.000000
50%       1450.000000
75%       2300.000000
max       7200.000000

In [319]:
df.isna().sum()

Order_ID          0
Order_Date        0
Customer_ID       7
City              6
Product_ID        0
Product_Name      0
Category          0
Quantity          5
Unit_Price_PKR    6
Discount_Rate     5
Payment_Method    7
Order_Status      0
dtype: int64

In [320]:
product.isna().sum()

Product_ID        0
Product_Name      0
Category          0
List_Price_PKR    0
Supplier          0
dtype: int64

Data cleaning
- Duplicate orders identify karein aur investigate karke duplicates remove karein.
- Missing Quantity, Unit_Price_PKR, Discount_Rate aur City ko handle karein.
- City names ko standardize karein, jaise lahore aur Karachi .
- Order_Date ko proper datetime format mein convert karein.

In [321]:
df.duplicated().sum()

np.int64(3)

In [322]:
df = df.drop_duplicates()

In [323]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())

In [324]:
df['Unit_Price_PKR'] = df['Unit_Price_PKR'].fillna(df['Unit_Price_PKR'].median())

In [325]:
df['Discount_Rate'] = df['Discount_Rate'].fillna(df['Discount_Rate'].median())

In [326]:
df['City'] = df['City'].fillna('unknown')

In [327]:
df['City'] = df['City'].str.strip().str.title()

In [328]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [329]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'City', 'Product_ID',
       'Product_Name', 'Category', 'Quantity', 'Unit_Price_PKR',
       'Discount_Rate', 'Payment_Method', 'Order_Status'],
      dtype='str')

Question 3: Sales Calculation
- Gross_Sales column banayein.
- Discount_Amount column banayein.
- Net_Sales calculate karein.
- Completed orders ki total net sales calculate karein.

In [330]:
df['Gross_Sales'] = df['Quantity'] * df['Unit_Price_PKR']

In [331]:
df['Discount_Amount'] = (df['Discount_Rate'] * df['Gross_Sales'] )/100

In [332]:
df['Net_Sales'] = df['Gross_Sales'] - df['Discount_Amount']

In [333]:
df[df['Order_Status'] == 'Completed']['Net_Sales'].sum()

np.float64(2667191.4077500002)

Question 4: Category-wise Analysis
- Har category ki total sales calculate karein.
- Har category ki total quantity sold find karein.
- Sabse zyada revenue wali category identify karein.
Functions: groupby(), agg(), sort_values()

In [334]:
df.groupby('Category')['Net_Sales'].count()

Category
Beauty            131
Electronics       150
Home & Kitchen    114
Sports            129
Stationery        127
Name: Net_Sales, dtype: int64

In [335]:
df.groupby('Category')['Quantity'].sum()

Category
Beauty            399.0
Electronics       446.0
Home & Kitchen    338.0
Sports            345.0
Stationery        391.0
Name: Quantity, dtype: float64

In [336]:
df.groupby('Category')['Net_Sales'].sum().idxmax()

'Electronics'

Question 5: Top Products
- Revenue ke hisaab se top 5 products find karein.
- Sabse zyada quantity mein sell hone wala product find karein.
- Har product ki average selling price calculate karein.

In [337]:
df.groupby('Product_Name')['Net_Sales'].sum().nlargest(5)

Product_Name
USB-C Hub           972048.330
Running Shoes       778366.440
Keyboard            493706.960
Yoga Mat            255701.585
Resistance Bands    224854.240
Name: Net_Sales, dtype: float64

In [338]:
df.groupby('Product_Name')['Quantity'].sum().nlargest(1)

Product_Name
USB-C Hub    180.0
Name: Quantity, dtype: float64

In [339]:
df.groupby('Product_Name')['Unit_Price_PKR'].mean()

Product_Name
Ballpoint Pens       245.312500
Coffee Mug           570.256410
Desk Organizer      1261.397059
Face Wash            773.000000
Keyboard            3147.884615
Moisturizer         1643.310811
Notebook Set         636.824324
Resistance Bands    1580.740741
Running Shoes       7076.842105
Storage Box         1445.972222
Sunscreen           1326.681818
USB-C Hub           5386.500000
Water Bottle         952.435897
Wireless Mouse      1781.052632
Yoga Mat            2686.756757
Name: Unit_Price_PKR, dtype: float64

Question 6: City-wise Analysis
- Kis city ki completed-order sales sabse zyada hain?
- Har city ke unique customers count karein.
- Har city ki average order value calculate karein.
- Lahore aur Karachi ki sales compare karein.

In [340]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'City', 'Product_ID',
       'Product_Name', 'Category', 'Quantity', 'Unit_Price_PKR',
       'Discount_Rate', 'Payment_Method', 'Order_Status', 'Gross_Sales',
       'Discount_Amount', 'Net_Sales'],
      dtype='str')

In [341]:
df[df['Order_Status'] == 'Completed'].groupby('City')['Net_Sales'].sum().idxmax()

'Rawalpindi'

In [342]:
df.groupby('City')['Customer_ID'].unique().count()

np.int64(9)

In [343]:
df.groupby(['City', 'Order_ID'])['Net_Sales'].sum().groupby('City').mean()

City
Faisalabad    5604.573708
Gujranwala    5690.354627
Islamabad     5766.716519
Karachi       7384.623948
Lahore        6891.830203
Multan        5245.791317
Peshawar      5588.842338
Rawalpindi    7126.477776
Unknown       4320.154167
Name: Net_Sales, dtype: float64

In [344]:
df[df['City'].isin(['Lahore', 'Karachi'])].groupby('City')['Net_Sales'].sum()

City
Karachi    598154.53975
Lahore     654723.86925
Name: Net_Sales, dtype: float64

Question 7: Monthly Sales Trend
- Har month ki sales calculate karein.
- Sabse zyada sales wala month find karein.
- Monthly revenue aur order count compare karein.

In [345]:
df['Year_Month'] = df['Order_Date'].dt.to_period('M')

In [346]:
df.groupby('Year_Month')['Net_Sales'].sum().idxmax()

Period('2025-10', 'M')

In [347]:
revenue = df.groupby('Year_Month')['Net_Sales'].sum()
orders = df.groupby('Year_Month')['Order_ID'].count()

comparison = pd.concat (
    [revenue, orders],
    axis=1,
    keys=['Monthly_Revenue', 'Order_Count']
)
comparison

            Monthly_Revenue  Order_Count
Year_Month
2025-01        250901.86475           45
2025-02        396687.37625           49
2025-03        383048.00075           62
2025-04        385356.01775           66
2025-05        250322.54650           47
2025-06        321966.09000           61
2025-07        424897.04000           68
2025-08        254326.64800           43
2025-09        251227.81500           47
2025-10        426696.54000           50
2025-11        331277.45125           57
2025-12        336680.73375           53

Question 8: Payment & Order Status
- Sabse popular payment method kaunsa hai?
- Completed, Returned aur Cancelled orders count karein.
- Returned aur Cancelled orders ka percentage calculate karein.

In [348]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'City', 'Product_ID',
       'Product_Name', 'Category', 'Quantity', 'Unit_Price_PKR',
       'Discount_Rate', 'Payment_Method', 'Order_Status', 'Gross_Sales',
       'Discount_Amount', 'Net_Sales', 'Year_Month'],
      dtype='str')

In [349]:
df['Payment_Method'].value_counts().idxmax()

'JazzCash'

In [350]:
df['Order_Status'].value_counts()

Order_Status
Completed    443
Cancelled    107
Returned     101
Name: count, dtype: int64

In [351]:
df['Order_Status'].value_counts()['Returned'] / len(df)* 100

np.float64(15.514592933947775)

In [352]:
df['Order_Status'].value_counts()['Cancelled'] / len(df)* 100

np.float64(16.43625192012289)

Question 9: Merge & Join
- Sales dataset ko product catalog ke saath Product_ID par merge karein.
- Transaction prices ko catalog list prices se compare karein.
- Supplier-wise product sales analyze karein.

In [353]:
merged_df = pd.merge(df,product,on='Product_ID',how='inner')

In [354]:
merged_df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'City', 'Product_ID',
       'Product_Name_x', 'Category_x', 'Quantity', 'Unit_Price_PKR',
       'Discount_Rate', 'Payment_Method', 'Order_Status', 'Gross_Sales',
       'Discount_Amount', 'Net_Sales', 'Year_Month', 'Product_Name_y',
       'Category_y', 'List_Price_PKR', 'Supplier'],
      dtype='str')

In [355]:
merged_df['Price_Difference'] = merged_df['Unit_Price_PKR'] - merged_df['List_Price_PKR']

In [356]:
merged_df[['Product_ID', 'Unit_Price_PKR', 'List_Price_PKR', 'Price_Difference']]

    Product_ID  Unit_Price_PKR  List_Price_PKR  Price_Difference
0         P002          3200.0            3200               0.0
1         P002          3200.0            3200               0.0
2         P013           780.0             780               0.0
3         P013           780.0             780               0.0
4         P013           780.0             780               0.0
..         ...             ...             ...               ...
646       P009           577.5             550              27.5
647       P003          4860.0            5400            -540.0
648       P013           819.0             780              39.0
649       P015          1417.5            1350              67.5
650       P005           250.0             250               0.0

[651 rows x 4 columns]

In [357]:
merged_df.groupby('Supplier')['Net_Sales'].sum()

Supplier
Metro Wholesale     1.997945e+06
PakTech Supplies    5.879365e+05
Prime Traders       5.036706e+05
Urban Goods         9.311775e+05
Name: Net_Sales, dtype: float64

Question 10: Final Business Insights
- Total completed-order revenue report karein.
- Top category, product aur city identify karein.
- Monthly sales trend summarize karein.
- Business improve karne ke liye 3 recommendations dein.
- Final cleaned dataset ko CSV mein export karein.

In [358]:
df[df['Order_Status'] == 'Completed']['Net_Sales'].sum()

np.float64(2667191.4077500002)

In [359]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'City', 'Product_ID',
       'Product_Name', 'Category', 'Quantity', 'Unit_Price_PKR',
       'Discount_Rate', 'Payment_Method', 'Order_Status', 'Gross_Sales',
       'Discount_Amount', 'Net_Sales', 'Year_Month'],
      dtype='str')

In [360]:
df.groupby('Category')['Net_Sales'].sum()

Category
Beauty             505902.939
Electronics       1658533.445
Home & Kitchen     338206.830
Sports            1258922.265
Stationery         259164.395
Name: Net_Sales, dtype: float64

In [361]:
df.groupby('City')['Net_Sales'].sum().idxmax()

'Lahore'

In [362]:
df.groupby('Product_Name')['Net_Sales'].sum().idxmax()

'USB-C Hub'

In [363]:
df.groupby('Year_Month')['Net_Sales'].sum()

Year_Month
2025-01    250901.86475
2025-02    396687.37625
2025-03    383048.00075
2025-04    385356.01775
2025-05    250322.54650
2025-06    321966.09000
2025-07    424897.04000
2025-08    254326.64800
2025-09    251227.81500
2025-10    426696.54000
2025-11    331277.45125
2025-12    336680.73375
Freq: M, Name: Net_Sales, dtype: float64

Top-selling products par focus: Jo products sabse zyada revenue generate karte hain, unka stock available rakho.



Low-performing categories ko analyze karo: Kam sales wali categories ke liye pricing, promotions aur customer demand check karo.



Monthly sales monitor karo: Low-sales months mein targeted discounts ya marketing campaigns test karo.

In [364]:
df.head()

,Order_ID,Order_Date,Customer_ID,City,Product_ID,Product_Name,Category,Quantity,Unit_Price_PKR,Discount_Rate,Payment_Method,Order_Status,Gross_Sales,Discount_Amount,Net_Sales,Year_Month
0,ORD-10001,2025-11-10,CUST-008,Multan,P002,Keyboard,Electronics,4.0,3200.0,0.10,Card,Completed,12800.0,12.80,12787.20,2025-11
1,ORD-10002,2025-09-19,CUST-071,Faisalabad,P002,Keyboard,Electronics,3.0,3200.0,0.20,Cash,Returned,9600.0,19.20,9580.80,2025-09
2,ORD-10003,2025-12-05,CUST-071,Multan,P013,Face Wash,Beauty,3.0,780.0,0.10,Bank Transfer,Completed,2340.0,2.34,2337.66,2025-12
3,ORD-10004,2025-02-03,CUST-050,Gujranwala,P013,Face Wash,Beauty,3.0,780.0,0.05,Cash,Completed,2340.0,1.17,2338.83,2025-02
4,ORD-10005,2025-10-04,CUST-064,Islamabad,P013,Face Wash,Beauty,5.0,780.0,0.00,Cash,Completed,3900.0,0.00,3900.00,2025-10

In [365]:
df.shape

(651, 16)

In [366]:
df.isna().sum()

Order_ID           0
Order_Date         3
Customer_ID        7
City               0
Product_ID         0
Product_Name       0
Category           0
Quantity           0
Unit_Price_PKR     0
Discount_Rate      0
Payment_Method     7
Order_Status       0
Gross_Sales        0
Discount_Amount    0
Net_Sales          0
Year_Month         3
dtype: int64

In [367]:
df['Customer_ID'] = df['Customer_ID'].fillna('Unknown')

In [368]:
df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')

In [369]:
df.isna().sum()

Order_ID           0
Order_Date         3
Customer_ID        0
City               0
Product_ID         0
Product_Name       0
Category           0
Quantity           0
Unit_Price_PKR     0
Discount_Rate      0
Payment_Method     0
Order_Status       0
Gross_Sales        0
Discount_Amount    0
Net_Sales          0
Year_Month         3
dtype: int64

In [370]:
df['Order_Date'] = df['Order_Date'].astype('object').fillna('Unknown')

In [371]:

df['Year_Month'] = df['Year_Month'].astype('object').fillna('Unknown')

In [372]:
df.isna().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
City               0
Product_ID         0
Product_Name       0
Category           0
Quantity           0
Unit_Price_PKR     0
Discount_Rate      0
Payment_Method     0
Order_Status       0
Gross_Sales        0
Discount_Amount    0
Net_Sales          0
Year_Month         0
dtype: int64

In [373]:
df.head()

,Order_ID,Order_Date,Customer_ID,City,Product_ID,Product_Name,Category,Quantity,Unit_Price_PKR,Discount_Rate,Payment_Method,Order_Status,Gross_Sales,Discount_Amount,Net_Sales,Year_Month
0,ORD-10001,2025-11-10 00:00:00,CUST-008,Multan,P002,Keyboard,Electronics,4.0,3200.0,0.10,Card,Completed,12800.0,12.80,12787.20,2025-11
1,ORD-10002,2025-09-19 00:00:00,CUST-071,Faisalabad,P002,Keyboard,Electronics,3.0,3200.0,0.20,Cash,Returned,9600.0,19.20,9580.80,2025-09
2,ORD-10003,2025-12-05 00:00:00,CUST-071,Multan,P013,Face Wash,Beauty,3.0,780.0,0.10,Bank Transfer,Completed,2340.0,2.34,2337.66,2025-12
3,ORD-10004,2025-02-03 00:00:00,CUST-050,Gujranwala,P013,Face Wash,Beauty,3.0,780.0,0.05,Cash,Completed,2340.0,1.17,2338.83,2025-02
4,ORD-10005,2025-10-04 00:00:00,CUST-064,Islamabad,P013,Face Wash,Beauty,5.0,780.0,0.00,Cash,Completed,3900.0,0.00,3900.00,2025-10

In [374]:
df.dtypes

Order_ID               str
Order_Date          object
Customer_ID            str
City                   str
Product_ID             str
Product_Name           str
Category               str
Quantity           float64
Unit_Price_PKR     float64
Discount_Rate      float64
Payment_Method         str
Order_Status           str
Gross_Sales        float64
Discount_Amount    float64
Net_Sales          float64
Year_Month          object
dtype: object

In [375]:
df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    errors='coerce'
)

In [376]:
df['Year_Month'] = df['Order_Date'].dt.to_period('M')

In [377]:
df.dtypes

Order_ID                      str
Order_Date         datetime64[us]
Customer_ID                   str
City                          str
Product_ID                    str
Product_Name                  str
Category                      str
Quantity                  float64
Unit_Price_PKR            float64
Discount_Rate             float64
Payment_Method                str
Order_Status                  str
Gross_Sales               float64
Discount_Amount           float64
Net_Sales                 float64
Year_Month              period[M]
dtype: object

In [378]:
df.isnull().sum()

Order_ID           0
Order_Date         3
Customer_ID        0
City               0
Product_ID         0
Product_Name       0
Category           0
Quantity           0
Unit_Price_PKR     0
Discount_Rate      0
Payment_Method     0
Order_Status       0
Gross_Sales        0
Discount_Amount    0
Net_Sales          0
Year_Month         3
dtype: int64

In [379]:
df.to_csv('cleaned_sales_dataset.csv', index=False)

In [380]:
pd.read_csv('cleaned_sales_dataset.csv')

,Order_ID,Order_Date,Customer_ID,City,Product_ID,Product_Name,Category,Quantity,Unit_Price_PKR,Discount_Rate,Payment_Method,Order_Status,Gross_Sales,Discount_Amount,Net_Sales,Year_Month
0,ORD-10001,2025-11-10,CUST-008,Multan,P002,Keyboard,Electronics,4.0,3200.0,0.10,Card,Completed,12800.0,12.80000,12787.20000,2025-11
1,ORD-10002,2025-09-19,CUST-071,Faisalabad,P002,Keyboard,Electronics,3.0,3200.0,0.20,Cash,Returned,9600.0,19.20000,9580.80000,2025-09
2,ORD-10003,2025-12-05,CUST-071,Multan,P013,Face Wash,Beauty,3.0,780.0,0.10,Bank Transfer,Completed,2340.0,2.34000,2337.66000,2025-12
3,ORD-10004,2025-02-03,CUST-050,Gujranwala,P013,Face Wash,Beauty,3.0,780.0,0.05,Cash,Completed,2340.0,1.17000,2338.83000,2025-02
4,ORD-10005,2025-10-04,CUST-064,Islamabad,P013,Face Wash,Beauty,5.0,780.0,0.00,Cash,Completed,3900.0,0.00000,3900.00000,2025-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,ORD-10647,2025-07-27,CUST-056,Multan,P009,Coffee Mug,Home & Kitchen,1.0,577.5,0.05,EasyPaisa,Completed,577.5,0.28875,577.21125,2025-07
647,ORD-10648,2025-02-13,CUST-042,Islamabad,P003,USB-C Hub,Electronics,3.0,4860.0,0.10,Cash,Returned,14580.0,14.58000,14565.42000,2025-02
648,ORD-10649,2025-01-13,CUST-026,Multan,P013,Face Wash,Beauty,2.0,819.0,0.00,JazzCash,Cancelled,1638.0,0.00000,1638.00000,2025-01
649,ORD-10650,2025-02-14,CUST-061,Faisalabad,P015,Sunscreen,Beauty,3.0,1417.5,0.00,Cash,Completed,4252.5,0.00000,4252.50000,2025-02
650,ORD-10104,2025-04-04,CUST-059,Rawalpindi,P005,Ballpoint Pens,Stationery,3.0,250.0,0.10,EasyPaisa,Returned,750.0,0.75000,749.25000,2025-04